name: Static Code Analyzers

on: [push]
jobs:
  ruby:
    name: Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
          bundler-cache: true

      # Required to install `rubocop` on Ruby 2.5.
      - run: gem install rubocop-ast:1.17.0

      - name: Run Rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: gemfile
          rubocop_extensions: ''
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: diff_context

      - name: Run Sorbet
        run: bundle exec srb tc
